CMAKE_MINIMUM_REQUIRED(VERSION 3.0.0)

LIST(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR}/modules)

# Automatically include all modules
FILE(
  GLOB FILES
  LIST_DIRECTORIES true
  "${CMAKE_MODULE_PATH}/*.cmake")

FOREACH(FILE IN LISTS FILES)
  INCLUDE("${FILE}")
ENDFOREACH()
